package live.lingting.framework.util

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * @author lingting 2024/12/27 16:55
 */
class HttpUtilsTest {

    @Test
    fun test() {
        assertTrue(HttpUtils.isHttpUrl("http://example.com/index.html"))
        assertTrue(HttpUtils.isHttpUrl("http://testsite.org:8080/about?a+b"))
        assertTrue(HttpUtils.isHttpUrl("http://demo.net/products?a=s j&2"))
        assertTrue(HttpUtils.isHttpUrl("http://mywebsite.io:3000/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://othersite.co/contact"))
        assertTrue(HttpUtils.isHttpUrl("http://example.com:8080/products"))
        assertTrue(HttpUtils.isHttpUrl("http://testsite.org/index.html"))
        assertTrue(HttpUtils.isHttpUrl("http://demo.net:3000/about"))
        assertTrue(HttpUtils.isHttpUrl("http://mywebsite.io/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://othersite.co:80/index.html"))
        assertTrue(HttpUtils.isHttpUrl("http://example.com/about"))
        assertTrue(HttpUtils.isHttpUrl("http://testsite.org:3000/products"))
        assertTrue(HttpUtils.isHttpUrl("http://demo.net/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://mywebsite.io:8080/contact"))
        assertTrue(HttpUtils.isHttpUrl("http://othersite.co/index.html"))
        assertTrue(HttpUtils.isHttpUrl("http://example.com:3000/contact"))
        assertTrue(HttpUtils.isHttpUrl("http://testsite.org/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://demo.net:8080/about"))
        assertTrue(HttpUtils.isHttpUrl("http://my-website.io/products"))
        assertTrue(HttpUtils.isHttpUrl("http://othersite.co:3000/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://example.com:80/about"))
        assertTrue(HttpUtils.isHttpUrl("http://testsite.org:80/products"))
        assertTrue(HttpUtils.isHttpUrl("http://demo.net:3000/contact"))
        assertTrue(HttpUtils.isHttpUrl("http://mywebsite.io:8080/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://othersite.co/index.html"))
        assertTrue(HttpUtils.isHttpUrl("http://example.com/blog"))
        assertTrue(HttpUtils.isHttpUrl("http://testsite.org:3000/about"))
        assertTrue(HttpUtils.isHttpUrl("http://demo.net:8080/products"))
        assertTrue(HttpUtils.isHttpUrl("http://mywebsite.io/contact"))
        assertTrue(HttpUtils.isHttpUrl("http://othersite.co:8080/index.html"))
        assertTrue(HttpUtils.isHttpUrl("https://bucket.oss-accelerate.aliyuncs.com/tid/uid/avatar/websocket_cid_t1_t2_f.jpg"))

        assertEquals("example.com", HttpUtils.pickHost("http://example.com/index.html"))
        assertEquals("testsite.org:8080", HttpUtils.pickHost("http://testsite.org:8080/about?a+b"))
        assertEquals("demo.net", HttpUtils.pickHost("http://demo.net/products?a=s j&2"))
        assertEquals("mywebsite.io:3000", HttpUtils.pickHost("http://mywebsite.io:3000/blog"))
        assertEquals("othersite.co", HttpUtils.pickHost("http://othersite.co/contact"))
        assertEquals("example.com:8080", HttpUtils.pickHost("http://example.com:8080/products"))
        assertEquals("testsite.org", HttpUtils.pickHost("http://testsite.org/index.html"))
        assertEquals("demo.net:3000", HttpUtils.pickHost("http://demo.net:3000/about"))
        assertEquals("mywebsite.io", HttpUtils.pickHost("http://mywebsite.io/blog"))
        assertEquals("othersite.co:80", HttpUtils.pickHost("http://othersite.co:80/index.html"))
        assertEquals("example.com", HttpUtils.pickHost("http://example.com/about"))
        assertEquals("testsite.org:3000", HttpUtils.pickHost("http://testsite.org:3000/products"))
        assertEquals("demo.net", HttpUtils.pickHost("http://demo.net/blog"))
        assertEquals("mywebsite.io:8080", HttpUtils.pickHost("http://mywebsite.io:8080/contact"))
        assertEquals("othersite.co", HttpUtils.pickHost("http://othersite.co/index.html"))
        assertEquals("example.com:3000", HttpUtils.pickHost("http://example.com:3000/contact"))
        assertEquals("testsite.org", HttpUtils.pickHost("http://testsite.org/blog"))
        assertEquals("demo.net:8080", HttpUtils.pickHost("http://demo.net:8080/about"))
        assertEquals("my-website.io", HttpUtils.pickHost("http://my-website.io/products"))
        assertEquals("othersite.co:3000", HttpUtils.pickHost("http://othersite.co:3000/blog"))
        assertEquals("example.com:80", HttpUtils.pickHost("http://example.com:80/about"))
        assertEquals("testsite.org:80", HttpUtils.pickHost("http://testsite.org:80/products"))
        assertEquals("demo.net:3000", HttpUtils.pickHost("http://demo.net:3000/contact"))
        assertEquals("mywebsite.io:8080", HttpUtils.pickHost("http://mywebsite.io:8080/blog"))
        assertEquals("othersite.co", HttpUtils.pickHost("http://othersite.co/index.html"))
        assertEquals("example.com", HttpUtils.pickHost("http://example.com/blog"))
        assertEquals("testsite.org:3000", HttpUtils.pickHost("http://testsite.org:3000/about"))
        assertEquals("demo.net:8080", HttpUtils.pickHost("http://demo.net:8080/products"))
        assertEquals("mywebsite.io", HttpUtils.pickHost("http://mywebsite.io/contact"))
        assertEquals("othersite.co:8080", HttpUtils.pickHost("http://othersite.co:8080/index.html"))
        assertEquals("bucket.oss-accelerate.aliyuncs.com", HttpUtils.pickHost("https://bucket.oss-accelerate.aliyuncs.com/tid/uid/avatar/websocket_cid_t1_t2_f.jpg"))

        assertFalse(HttpUtils.isHttpUrl("http://example.com:abc/about"))
        assertFalse(HttpUtils.isHttpUrl("http://testsite.org:xyz/products"))
        assertFalse(HttpUtils.isHttpUrl("http://demo.net:12a/blog"))
        assertFalse(HttpUtils.isHttpUrl("http://mywebsite.io:abcdef/contact"))
        assertFalse(HttpUtils.isHttpUrl("http://othersite.co:aaa/index.html"))
        assertFalse(HttpUtils.isHttpUrl("http://invalid@domain.com:8080/about"))
        assertFalse(HttpUtils.isHttpUrl("http://ab+c-domain.net/products"))
        assertFalse(HttpUtils.isHttpUrl("http://test_site.org:3000/blog"))
        assertFalse(HttpUtils.isHttpUrl("http://myweb_site.io/contact"))
        assertFalse(HttpUtils.isHttpUrl("http://other_site.co/index.html"))
        assertFalse(HttpUtils.isHttpUrl("htp://example.com:8080/about"))
        assertFalse(HttpUtils.isHttpUrl("htp://testsite.org/products"))
        assertFalse(HttpUtils.isHttpUrl("htp://demo.net:3000/blog"))
        assertFalse(HttpUtils.isHttpUrl("htp://mywebsite.io/contact"))
        assertFalse(HttpUtils.isHttpUrl("htp://othersite.co/index.html"))
        assertFalse(HttpUtils.isHttpUrl("example.com:8080/products"))
        assertFalse(HttpUtils.isHttpUrl("mywebsite.io/blog"))
        assertFalse(HttpUtils.isHttpUrl("othersite.co/contact"))
        assertFalse(HttpUtils.isHttpUrl("testsite.org/index.html"))
        assertFalse(HttpUtils.isHttpUrl("demo.net:3000/about"))
    }
}
